---
apt: https://pkg.jenkins.io/debian-stable
apt_packages:
  - mc
  - jenkins
  - nano
  - nginx
services:
  - jenkins
  - nginx
packages:
  - openjdk-8-jre-headless
  - wget
  - git
virual_hosts:
<<<<<<< HEAD
  - { name: "master.jenkins.by" }
=======
- { name: "master.jenkins.by" }
site: master.jenkins.by
>>>>>>> 72c6e1cd94deeb1af1a14935cd7ca77ff2ab1f13
