---
- name: Install Vagrant and VirtualBox
  tags: install
  yum:
    name: "{{yum_packages}}"
    state: latest
- name: Install Vagrant
  gem:
    name: "{{gem_packages}}"
    state: latest
- name: Create vagrant work directory
  tags: install
  shell: "mkdir ~/deploy && cd ~/deploy && vagrant init"
  args:
    warn: false
- name: Vagrant remove Vagrantfile
  tags: install
  file:
    path: "~/deploy/Vagrantfile"
    state: absent
- name: Copy private ssh key for vagrant machine
  tags: install
  copy:
    src: "~/.ssh/id_rsa"
    dest: ~/deploy/
    mode: 0600
- name: Copy public ssh key for vagrant machine
  tags: install
  copy:
    src: "~/.ssh/id_rsa.pub"
    dest: ~/deploy/
    mode: 0644
- name: Copy working Vagranfile to repository
  tags: install
  copy:
    src: Vagrantfile
    dest: ~/deploy/
- name: change permissions for folder deploy
  tags: install
  file:
    dest: ~/deploy
    owner: vagrant
    group: vagrant
    recurse: yes
- name: Deploy vagrant machine
  tags: up
  shell: "cd ~/deploy/ && vagrant up"
...
