---
- name: Install Vagrant and VirtualBox
  tags: install
  yum:
    name: "{{yum_packages}}"
    state: latest
- name: Install Vagrant
  gem:
    name: "{{gem_packages}}"
    state: latest
- name: Create vagrant work dirictory
  tags: install
  shell: "mkdir /home/deploy && cd /home/deploy && vagrant init"
- name: Vagrant remove Vagrantfile
  tags: install
  file:
    path: "/home/deploy/Vagrantfile"
    state: absent
- name: Copy private ssh key for vagrant machine
  tags: install
  copy:
    src: "~/.ssh/id_rsa"
    dest: /home/deploy/
    mode: 0600
- name: Copy public ssh key for vagrant machine
  tags: install
  copy:
    src: "~/.ssh/id_rsa.pub"
    dest: /home/deploy/
    mode: 0644
- name: Copy working Vagranfile to repository
  tags: install
  copy:
    src: config/Vagrantfile
    dest: /home/deploy/
- name: Deploy vagrant machine
  shell: "cd /home/deploy/ && vagrant up"
...
