---
all:
  children:
    vsphere:
      hosts:
        vm1:
          ansible_user: vagrant
          ansible_host: 10.50.80.104
          ansible_ssh_port: 8022
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
        vm2:
          ansible_user: vagrant
          ansible_host: 10.50.80.104
          ansible_ssh_port: 8023
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
...
