---
all:
  children:
    vagrant:
      hosts:
        vm1:
          ansible_host: 10.50.80.104
          ansible_ssh_port: 8022
        vm2:
          ansible_host: 10.50.80.104
          ansible_ssh_port: 8023
...
