---
- name: install epel dependense
  yum: 
    name: "{{ epel }}"
    state: latest
- name: Nginx. Redhat
  yum:
    name: "{{ yum_nginx }}" 
    state: latest
- name: Nginx. Start
  service:
    name: nginx
    state: started
    enabled: yes
- name: Copy site config for RedHat OS
  tags: cp_site
  copy:
    src: "{{ item }}"
    dest: "{{ sites_rh }}"
  with_items:
    - devops.by/devops.by.conf
    - devops.ru/devops.ru.conf
