---
- name: Apache2. Redhat
  yum:
    name: "{{yum_http}}" 
#    name: pkg={{ item }}
#    register: out
    state: latest
#- name: Out install progress
#  debug: var=out.stdout_lines
- name: Apache2. Remove wecome config
  file:
    path: "/etc/httpd/conf.d/welcome.conf"
    state: absent
- name: Apache2. Start
  service:
    name: httpd
    state: started
    enabled: yes
