---
- name: install epel dependense
  yum: 
    name: "{{ epel }}"
    state: latest
- name: Nginx. Redhat
  yum:
    name: "{{ yum_nginx }}" 
    state: latest
- name: Nginx. Start
  service:
    name: nginx
    state: started
    enabled: yes
