---
epel:
 - epel-release
yum_nginx:
  - mc
  - nano
  - nginx
apt_nginx:
  - nginx
  - mc
  - vim
virual_hosts:
  - { ip: "127.0.0.1", name: "devops.by" }
  - { ip: "127.0.0.1", name: "devops.ru" } 
index_ru: "/var/www/devops_ru/"
index_by: "/var/www/devops_by/"
index:
  - "{{ index_ru }}"
  - "{{ index_by }}"
sites: "/etc/nginx/sites-available/"
my_site:
  - devops/devops.by
  - devops/devops.ru